### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by boblq** [googlecodelabs/android-wavemaker#5]
I could not get this to build until I went into the SDK Tools tab at 
Tools > Appearance & Behavior > System Setttings > Android SDK > SDK Tools
and checked the CMake and LLDB boxes in order to install that capability. 

I am an Android newbie and it took me a while to figure this out. You might want to mention it in your blog post. The error message from Android Studio was pretty cryptic and was of no use to me in finding a solution to the problem. 

I can understand that this small configuration problem would not occur since you must have set up your environment some time back and it would not occur to you that someone (a noob to Android like like me) would not know to do it. 

The code is working fine now and will be of real use to me in the project I am beginning. Other than this point the post is clear and the code clean. 

![android sdk settings_005](https://user-images.githubusercontent.com/432688/35500490-981a1ba0-0511-11e8-986c-4f1121d0b1ba.png)

Bob La Quey

PS. I am not sure if LLDB is needed but I saw a clue on stackoverflow that led me to check it. It is a debugger, so having installed should be useful when I get a little further into my project.

**Comment by dturner** [comment]
Thank you for submitting this issue. I have updated the codelab prerequisites to include this step. https://codelabs.developers.google.com/codelabs/making-waves-1-synth/#0
