### ISSUE TITLE
Set buffer size fails due to syntax error

### ISSUE THREAD

**Issue by dhaval22** [googlecodelabs/android-wavemaker#6]
// Sets the buffer size. 
    AAudioStream_setBufferSizeInFrames(
           stream_, AAudioStream_getFramesPerBurst(stream_) * kBufferSizeInBursts);
kBuffersToUse); //  <-- this seems misplaced

**Comment by dturner** [comment]
Many thanks for spotting and reporting this issue! You're right, it's a bug. Fixed now.
