### ISSUE TITLE
code explanation example different from code in AudioEngine.cpp

### ISSUE THREAD

**Issue by elseanox** [googlecodelabs/android-wavemaker#8]
The contents of the error logging instruction in the code and explanation of the code differs slightly.

In the explanation of what happens when a stream is being opened, the error message is "Error opening stream"

<pre>
if (result != AAUDIO_OK){
__android_log_print(ANDROID_LOG_ERROR, "Error opening stream", AAudio_convertResultToText(result));
        return false;
}
</pre>

In the original code it reads "AudioEngine"

<pre>
if (result != AAUDIO_OK){
__android_log_print(ANDROID_LOG_ERROR, "AudioEngine", "Error opening stream %s", AAudio_convertResultToText(result));
        return false;
    }
</pre>

**Comment by elseanox** [comment]
Same thing for:

<pre>
[code]
    oscillator_.setSampleRate(sampleRate); 
</pre>

vs
<pre>
[docs]
    oscillator_->setSampleRate(sampleRate);
</pre>

**Comment by elseanox** [comment]
Again for:
<pre>
[code]
  void AudioEngine::setToneOne(bool isToneOn) {
    oscillator_.setWaveOn(isToneOn);
}
</pre>
vs

<pre>
[docs]
    void AudioEngine::setToneOn(bool isToneOn) {
      oscillator_->setWaveOn(isToneOn);
}
</pre>

**Comment by dturner** [comment]
Thanks so much for reporting these errors. Docs have been corrected.
